# a _config.yml file tells Jekyll some basics about your project. In this example, we're telling Jekyll the name of our site and what version of Markdown we'd like to use/

name: Hank Quinlan, Horrible Cop
markdown: kramdown
